#!/usr/bin/env node
const {basename, join} = require('path')
const {sync, watch} = require('../lib/sync')
const args = process.argv.slice(2)

const options = {
  debug: !args.includes('--quiet')
}

if (args.includes('--watch')) {
  const watcher = watch(options)
  process.on('exit', () => watcher.close())
} else {
  sync(options)
}
