#!/usr/bin/env node
const {basename, join} = require('path')
const {sync, watch} = require('../lib/sync')
const args = process.argv.slice(2)

const sourceDir = join(__dirname, '../../modules')
const destDir = join(__dirname, '../pages/css')

const options = {
  sourceDir,
  destDir,
  debug: !args.includes('--quiet'),
  map: {
    '../CHANGELOG.md': 'whats-new/changelog.md',
    'primer/README.md': false, // 'packages/primer.md',
    'primer-base/README.md': false, // 'support/base.md',
    'primer-core/README.md': false, // 'packages/primer-core.md',
    'primer-layout/README.md': 'objects/layout.md',
    'primer-layout/docs/*.md': path => `objects/${basename(path)}`,
    'primer-marketing-support/README.md': 'support/marketing-variables.md',
    'primer-marketing-type/README.md': 'utilities/marketing-type.md',
    'primer-marketing-utilities/README.md': false, // 'utilities/marketing.md',
    'primer-marketing-utilities/docs/*.md': path => `utilities/marketing-${basename(path)}`,
    'primer-marketing/README.md': false, // 'packages/primer-marketing.md',
    'primer-product/README.md': false, // 'packages/primer-product.md',
    'primer-support/README.md': false, // 'support/index.md',
    'primer-support/docs/*.md': path => `support/${basename(path)}`,
    'primer-table-object/README.md': 'objects/table-object.md',
    'primer-utilities/README.md': false, // 'utilities/index.md',
    'primer-utilities/docs/*.md': path => `utilities/${basename(path)}`,
    // this is a catch-all rule that needs to go last so that it doesn't override others
    'primer-*/README.md': path => `components/${shortName(path)}.md`,
  }
}

if (args.includes('--watch')) {
  const watcher = watch(options)
  process.on('exit', () => watcher.close())
} else {
  sync(options)
}

function shortName(path) {
  return path.match(/primer-([-\w]+)/)[1]
}
