#!/bin/bash
set -e

branch=$TRAVIS_PULL_REQUEST_BRANCH

# only publish canary releases on non-release or master branches
if
  [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]] &&
  [[ !("$branch" =~ ^release) ]] &&
  [[ !("$branch" = "master") ]]
then
  script/release-pr --yes
fi
