#!/usr/bin/env bash

yarn global add @axe-core/cli

# https://stackoverflow.com/a/21189044
parse_yaml() {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\)\($w\)$s:$s\"\(.*\)\"$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"\n", "'$prefix'",vn, $2, $3);
      }
   }'
}

# Find all nav paths for component pages
nav_paths=($(parse_yaml docs/src/@primer/gatsby-theme-doctocat/nav.yml | grep "/components/" | awk -F "=" '{print $2}'))

# Exclude known violations
# DO NOT ADD TO THIS LIST
needs_to_be_fixed=(
  /components/autocomplete
  /components/avatars
  /components/box
  /components/buttons
  /components/header
  /components/markdown
  /components/progress
  /components/select-menu
)

echo "############################################################"
echo "WARNING"
echo "The following paths will be excluded from this automated accessibility check."
echo "They contain known violations and should be addressed:"
printf '%s\n' "${needs_to_be_fixed[@]}"
echo "############################################################"

# Generate doc urls 
declare -a doc_urls

for i in "${nav_paths[@]}"; 
do
  if [[ " ${needs_to_be_fixed[*]} " =~ " ${i} " ]]; then
    continue
  else
    doc_url="localhost:8000$i"
    doc_url=("${doc_url//\"/}")
    doc_urls+=$doc_url
fi
done

# axe $doc_urls --save docs-example-accessibility.json --include "iframe" --disable html-has-lang,frame-title,page-has-heading-one,region,color-contrast,landmark-unique,landmark-one-main --exit --show-errors
axe $doc_urls --include "iframe" --disable html-has-lang,frame-title,page-has-heading-one,region,color-contrast,landmark-unique,landmark-one-main