#!/bin/sh
# Usage: script/cibuild
# CI build script.
# This is tailored for the janky build machines.
set -e

# change into root dir and setup path
cd $(dirname "$0")/..
PATH="$(pwd)/bin:$(pwd)/script:/usr/share/rbenv/shims:$PATH"

# Write commit we're building at
git log -n 1 || true
echo

bundle install
bundle exec rake test
