#!/bin/bash
set -e

# reads the tag either from $NPM_TAG or first positional arg:
# script/compare-published [tag]
tag=${1:-${NPM_TAG:-latest}}

packages=$($(dirname $0)/get-packages)

# tabular output separator for column(1)
s=,

echo "📦  Comparing Primer modules published @${tag}..."
(
    echo "module${s}tag${s}published${s}local"
    for package in $packages; do
        module=$(jq -r .name "$package/package.json")
        v_published=$(npm info "$module@$tag" .version)
        v_local=$(jq -Mr .version "$package/package.json")
        echo "${module}${s}${tag}${s}${v_published:-x}${s}${v_local}"
    done
) | column -t -s=${s}
