#!/bin/bash
set -e

if [ -z "$NOW_TOKEN" ]; then
    echo "NOW_TOKEN is not set; skipping docs deployment"
else
    cp modules/primer/build/build.css docs/static/primer.css
    cd docs
    npm run sync

    version=$(jq -r .version ../modules/primer/package.json)
    actual=$(jq -r .dependencies.primer package.json)

    # here, we need to manually update the primer dependency
    # version to the one that we published
    echo "primer has '$version' in package.json; docs wants '$actual'"
    jq ".dependencies.primer = \"$version\"" package.json > package.json.tmp
    mv package.json.tmp package.json

    now="now --token=$NOW_TOKEN"
    $now | tee now-url.txt
    url=$(cat now-url.txt)
    npx commit-status success docs "deployed primer@$version to $url" "$url"
    if [[ $TRAVIS_EVENT_TYPE = "pull_request" ]]; then
        branch=$TRAVIS_PULL_REQUEST_BRANCH
    else
        branch=$TRAVIS_BRANCH
    fi
    alias="primer-css-${branch//\./-}.now.sh"
    echo "aliasing..."
    $now alias $url $alias
    url="https://$alias"
    npx commit-status success docs "deployed primer@$version to $url" "$url"
fi
