#!/bin/bash
set -e

branch="${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}"
echo "[deploy] branch = '$branch'"

if [[ "$@" = "--dry-run" ]]; then
  args="--skip-git --skip-npm"
else
  args=$@
fi

if [[ "$branch" = master ]]; then
    script/release $args
elif [[ "$branch" =~ ^release- ]]; then
    script/release-candidate $args
else
    script/release-pr $args
fi
