#!/bin/bash
set -e

file=publish-files.log
if [[ -f $file ]]; then
    echo "deleting all files listed in $file..."
    cat $file | xargs rm -rfv
    rm $file
fi

if [[ "$GITHUB_REF" = "refs/heads/master" ]]; then
    npm run --silent publish-storybook || (
        echo "Whoops! Failed to publish Storybook. This is not a fatal error."
    )
fi

# TODO: remove this in v13
rm -rf build/
