#!/bin/bash
set -e

# generate the build directory
npm run --silent dist

# run the bundle size and selector diff reports
script/run-reports

files=$(git ls-files src | sed -e 's#^src/##' | sed -e 's#/.*$##' | sort -u)
echo $files > publish-files.log
cd src
cp -rv $files ..
cd -
