#!/bin/bash

npx action-status --context="$PUBLISH_STATUS_CONTEXT" --state=pending --description="publishing $version..."

# generate the build directory
npm run dist

files=$(git ls-files src | sed -e 's#^src/##' | sed -e 's#/.*$##' | sort -u)
echo $files > publish-files.txt
cd src
cp -rv $files ..
cd -
