#!/bin/bash
set -e

echo "📦  Publishing latest release..."

# note: try-publish should exit cleanly if it hits a published version
npx lerna exec --ignore='@primer/css-docs' $@ -- $(pwd)/script/try-publish

# Build and publish storybook
npx build-storybook -o build
script/publish-storybook
