#!/bin/bash
set -e
echo "👌  Publishing release candidate..."

npm_tag=rc

# if this is the same version, we need to bump the prerelease
# for all of the modules using the same prerelease identifier
echo "Updating all module versions in place..."
echo
module_dirs=modules/primer-*
for module_dir in $module_dirs; do
  module=$(basename $module_dir)
  $(dirname $0)/bump-rc $module
done

# publish all the things!
$(dirname $0)/notify pending

# note: this should NOT fail, so --bail=true applies
$(npm bin)/lerna exec -- npm publish --tag=$npm_tag

$(dirname $0)/notify success
