#!/bin/bash
set -e

if [[ "$@" = "--dry-run" ]]; then
  publish_args="--skip-git --skip-npm"
else
  publish_args=$@
fi

echo "🦜 Publishing canary release..."
npx lerna publish --canary --exact --npm-tag=rc $publish_args

echo "📓  Generating CHANGELOG..."
npx lerna-changelog
