#!/bin/bash
set -e
echo "📦  Publishing latest release..."

$(dirname $0)/notify pending

# note: try-publish should exit cleanly if it detects a duplicate
# published version
$(npm bin)/lerna exec -- $(dirname $0)/try-publish

$(dirname $0)/github-release || {
  $(dirname $0)/notify error
  exit 1
}

$(dirname $0)/notify success
