#!/bin/bash
set -e

echo "📦  Publishing latest release..."

# note: try-publish should exit cleanly if it detects a duplicate
# published version
npx lerna exec $@ -- script/try-publish

# Build and publish storybook
npx build-storybook -o build
script/publish-storybook

script/generate-changelog
