#!/bin/bash
set -e

disables=$(stylelint src --quiet --report-needless-disables -f unix | grep '^/')

while IFS= read -r line; do
  case $line in
    (*:*:*:*) file=${line%:*}
  esac
  echo $file
done < <(echo "$disables")
