#!/bin/bash
set -e

function log() {
  echo "$@" 1>&2
}

function warn() {
  echo "$@" 1>&2
}

pkg="@primer/css"
path="dist/stats/primer.json"
cp "tmp/node_modules/@primer/css/dist/stats/primer.json" before.json

cp $path after.json

key=".selectors.values[]"
jq -r $key before.json > before.txt
jq -r $key after.json > after.txt

diff -u {before,after}.txt

rm {before,after}.{json,txt}
