#!/usr/bin/env node
const dot = require("dot-component")
const fse = require("fs-extra")
const yargs = require("yargs")
  .option("set", {
    describe: "Set key 'x' in the form --set.x=foo",
    alias: "s",
  })
  .option("del", {
    describe: "Delete the provided key",
    alias: "d",
  })
const opts = yargs.argv
const args = opts._

const ops = []

if (opts.set && typeof opts.set === "object") {
  Object.entries(opts.set).forEach(([key, val]) => {
    ops.push(json => dot.set(json, key, val))
  })
}

if (opts.del) {
  const dels = Array.isArray(opts.del) ? opts.del : [opts.del]
  dels.forEach(key => {
    ops.push(json => dot.set(json, key, undefined))
  })
}

const UTF = "utf8"

const tasks = args.map(filename => {
  return fse.readFile(filename, UTF)
    .then(JSON.parse)
    .then(json => {
      ops.forEach(op => op(json))
      return json
    })
    .then(json => JSON.stringify(json, null, "  "))
    .then(str => fse.writeFile(filename, str, UTF))
    .then(() => filename)
})

Promise.all(tasks)
  .catch(error => {
    console.log(error)
    process.exit(1)
  })
  .then(files => {
    if (files.length > 1) {
      console.warn("wrote %d files", files.length)
    } else {
      console.warn("wrote %s:", files[0])
      return fse.readFile(files[0], UTF)
        .then(str => console.warn(str))
    }
  })
  .then(() => process.exit(0))
