#!/usr/bin/env node
const sync = require('../lib/sync')
const args = process.argv.slice(2)

const options = {
  debug: !args.includes('--quiet'),
  watch: args.includes('--watch')
}

sync(options)
  .then(files => {
    const built = Object.keys(files)
    console.warn(`built ${built.length} files:`)
    for (const file of built) {
      console.warn(`- ${file}`)
    }
  })
  .catch(error => {
    console.error(error)
    process.exitCode = 1
  })
