#!/bin/bash
set -e

if [[ $# -lt 1 ]]; then
  echo "You must provide a version!"
  exit 1
fi

version=$1
module=${2:-primer-css}

cd modules/$module
echo "${module}@$(jq -r .version package.json) => ${version}"
npm version --no-git ${@:1} > /dev/null
