name: changelog
on:
  push:
    branches:
      - 'release-*'
      - '*changelog*'
jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 11
      - name: install
        run: npm install
      - name: changelog
        run: script/changelog.js
